### ISSUE TITLE
Current version

### ISSUE THREAD

**Issue by BlackPhrase** [nagist/metahook#2]
Hey Nagi!
Which version this repo is?
I have a [Metahook Plus 0.4](https://github.com/headcrab-garage/Metahook-Plus-0.4) from 2014 and it has more interfaces but less plugins code

P.S.: Do you have any newer version?

**Comment by hzqst** [comment]
The interfaces in MHP0.3 is enough for me

**Comment by StLein** [comment]
Need wait GoldSrcEx ...


发送自 Outlook<http://aka.ms/weboutlook>

________________________________
发件人: Sh1ft0x0EF <notifications@github.com>
发送时间: 2017年3月26日 11:34:05
收件人: nagist/metahook
抄送: Subscribed
主题: [nagist/metahook] Current version (#2)


Hey Nagi!
Which version this repo is?
I have a Metahook Plus 0.4<https://github.com/Sh1ft0x0EF/Metahook-Plus-0.4> from 2014 and it has more interfaces but less plugins code

P.S.: Do you have any newer version?

―
