### ISSUE TITLE
[Crash]VS2017

### ISSUE THREAD

**Issue by missing233** [nagist/metahook#3]
VS2017(v141) VS2013(v120_xp)
Game crashed.

**Comment by HowToDoThis** [comment]
Directly upgrade project and build with v141 not supported, need to modified code. Check this post from Metahook吧 by 展鸿丶->[Build Metahook With VS2017](https://tieba.baidu.com/p/6077663246)
But not very recommend with this solution, bigger file size (around 120KB) and might unable used this method on future vs2017.
Recommend download vs2005 and build it, smaller file size (around 40KB) !!!
